### ISSUE TITLE
[Tracking] Sharelink Parsing

### ISSUE THREAD

**Issue by shanoaice** [Shadowsocks-NET/Aurum#1]
This issue tracks the sharelink parsing functionality of the Aurum main library.
- Protocol:
  - [x] VMess
  - [ ] VLESS (obsolete) *(post-v0)*
  - [x] Shadowsocks SIP002
  - [x] Shadowsocks SIP002 with plugins *(post-v0)*
  - [ ] Trojan (proposal) *(post-v0)*
- Transport
  - [x] TCP
  - [x] KCP
  - [x] QUIC
  - [x] gRPC
  - [x] HTTP/2
  - [x] WebSocket
- Security
  - [x] TLS
  - [ ] ~~XTLS~~

**Comment by shanoaice** [comment]
Phase 1 - full VMess support, done.

**Comment by shanoaice** [comment]
All non-post v0 task done.
