### ISSUE TITLE
[Tracking] Basic Functionalities

### ISSUE THREAD

**Issue by shanoaice** [Shadowsocks-NET/Aurum#2]
This issue tracks basic functionalities of the main library:
- [x] Sharelink Parsing
- Generic
  - [x] Inbound/Outbound
  - [x] Routing
- v2fly/v2ray-core
  - [ ] Inbound/Outbound Generation
  - [x] Routing
- sing-box
  - [ ] Inbound/Outbound Generation
  - [ ] Routing
- [ ] Filesystem Functionalities (Asset Management, On-Disk Configuration Generation)
- [ ] Subscription
- [ ] Statistics *(post-v0)*
- [x] Process Wrapping & Control
- [x] Logging
